//
// SearchResponseItemOwnerDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResponseItemOwnerDTO: Codable, JSONEncodable, Hashable {

    public var login: String
    public var avatarUrl: String

    public init(login: String, avatarUrl: String) {
        self.login = login
        self.avatarUrl = avatarUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case login
        case avatarUrl = "avatar_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(login, forKey: .login)
        try container.encode(avatarUrl, forKey: .avatarUrl)
    }
}

