//
// SearchResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchResponseDTO: Codable {

    public var items: [SearchResponseItemDTO]

    public init(items: [SearchResponseItemDTO]) {
        self.items = items
    }


}

