//
// SearchResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchResponseDTO: Codable {

    public var totalCount: Int
    public var items: [SearchResponseItemDTO]

    public init(totalCount: Int, items: [SearchResponseItemDTO]) {
        self.totalCount = totalCount
        self.items = items
    }

    public enum CodingKeys: String, CodingKey { 
        case totalCount = "total_count"
        case items
    }


}

